using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Avalonia;
using Avalonia.Media;

namespace PdfEditorApp.Plugins.CSharpEditor.Services.Extensibility.Theming.Layout;

/// <summary>
/// Writes <c>Styles/Tokens/StudioLayoutTokens.axaml</c>: every layout token at the default layout, so the tokens resolve
/// wherever the palette is included, before (or without) the theme engine laying anything out. A test keeps the file and
/// <see cref="LayoutTokenMapper"/> in step; <c>UiSnapshots layout-tokens</c> rewrites it.
/// </summary>
public static class LayoutTokenXaml
{
    public const string RelativePath = "Styles/Tokens/StudioLayoutTokens.axaml";

    public static string Generate()
    {
        var dark = LayoutTokenMapper.Map(LayoutSpec.Default, isDark: true);
        var light = LayoutTokenMapper.Map(LayoutSpec.Default, isDark: false);
        var schemeKeys = dark.Keys.Where(k => !Equals(Format(dark[k]), Format(light[k]))).ToHashSet(StringComparer.Ordinal);

        var xaml = new StringBuilder();
        xaml.AppendLine("<!-- Generated by LayoutTokenXaml from LayoutTokenMapper (the default layout). Don't edit by hand: -->");
        xaml.AppendLine("<!-- run `dotnet tools/UiSnapshots/bin/Debug/net10.0/UiSnapshots.dll layout-tokens` after changing the mapper. -->");
        xaml.AppendLine("<ResourceDictionary xmlns=\"https://github.com/avaloniaui\"");
        xaml.AppendLine("                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">");
        xaml.AppendLine("    <ResourceDictionary.ThemeDictionaries>");
        foreach (var (name, tokens) in new[] { ("Dark", dark), ("Light", light) })
        {
            xaml.AppendLine($"        <ResourceDictionary x:Key=\"{name}\">");
            foreach (var key in tokens.Keys.Where(schemeKeys.Contains).Order(StringComparer.Ordinal)) xaml.AppendLine("            " + Element(key, tokens[key]));
            xaml.AppendLine("        </ResourceDictionary>");
        }

        xaml.AppendLine("    </ResourceDictionary.ThemeDictionaries>");
        foreach (var key in dark.Keys.Where(k => !schemeKeys.Contains(k)).Order(StringComparer.Ordinal)) xaml.AppendLine("    " + Element(key, dark[key]));
        xaml.AppendLine("</ResourceDictionary>");
        return xaml.ToString().Replace("\r\n", "\n");
    }

    private static string Element(string key, object value) => value switch
    {
        double => $"<x:Double x:Key=\"{key}\">{Format(value)}</x:Double>",
        CornerRadius => $"<CornerRadius x:Key=\"{key}\">{Format(value)}</CornerRadius>",
        Thickness => $"<Thickness x:Key=\"{key}\">{Format(value)}</Thickness>",
        FontFamily => $"<FontFamily x:Key=\"{key}\">{Format(value)}</FontFamily>",
        FontWeight => $"<FontWeight x:Key=\"{key}\">{Format(value)}</FontWeight>",
        BoxShadows => $"<BoxShadows x:Key=\"{key}\">{Format(value)}</BoxShadows>",
        _ => throw new NotSupportedException($"Layout token '{key}' has a type the generator doesn't write: {value.GetType().Name}"),
    };

    /// <summary>A token value as XAML writes it.</summary>
    public static string Format(object value) => value switch
    {
        double d => Number(d),
        CornerRadius c => $"{Number(c.TopLeft)},{Number(c.TopRight)},{Number(c.BottomRight)},{Number(c.BottomLeft)}",
        Thickness t => $"{Number(t.Left)},{Number(t.Top)},{Number(t.Right)},{Number(t.Bottom)}",
        FontFamily f => string.Join(", ", f.FamilyNames), // every fallback: the first font is often not installed
        FontWeight w => w.ToString(),
        BoxShadows s => s.Count == 0 ? "0 0 0 0 #00000000" : string.Join(", ", Enumerable.Range(0, s.Count).Select(i => Shadow(s[i]))),
        _ => value.ToString() ?? string.Empty,
    };

    private static string Shadow(BoxShadow s) =>
        $"{Number(s.OffsetX)} {Number(s.OffsetY)} {Number(s.Blur)} {Number(s.Spread)} #{s.Color.A:X2}{s.Color.R:X2}{s.Color.G:X2}{s.Color.B:X2}";

    private static string Number(double value) => value.ToString("0.##", CultureInfo.InvariantCulture);
}
