using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PdfEditorApp.Plugins.CSharpEditor.Models;
using PdfEditorApp.Plugins.CSharpEditor.Models.Server;

namespace PdfEditorApp.Plugins.CSharpEditor.Services.Server;

public static class FryServerAspNetCoreExporter
{
    public static string ExportToMinimalApiProgramCs(FryServerDocumentItem document)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by FrySharp from .fryserver");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("var builder = WebApplication.CreateBuilder(args);");
        sb.AppendLine();

        if (document.ServerConfig.EnableCors)
        {
            sb.AppendLine("builder.Services.AddCors(options =>");
            sb.AppendLine("{");
            sb.AppendLine("    options.AddDefaultPolicy(policy =>");
            sb.AppendLine("        policy.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());");
            sb.AppendLine("});");
            sb.AppendLine();
        }

        sb.AppendLine("var app = builder.Build();");
        sb.AppendLine();

        if (document.ServerConfig.EnableCors)
        {
            sb.AppendLine("app.UseCors();");
            sb.AppendLine();
        }

        var prefix = document.ServerConfig.ApiPrefix?.TrimEnd('/') ?? string.Empty;
        if (!string.IsNullOrEmpty(prefix) && !prefix.StartsWith('/')) prefix = "/" + prefix;

        // Startup code (if any)
        foreach (var startupCell in document.Cells.Where(c => c.Enabled && c.Type == FryServerCellType.Startup))
        {
            sb.AppendLine($"// Startup Seed: {startupCell.Title}");
            sb.AppendLine(startupCell.Source);
            sb.AppendLine();
        }

        // Endpoint cells
        foreach (var cell in document.Cells.Where(c => c.Enabled && c.Type == FryServerCellType.Endpoint))
        {
            var route = $"{prefix}{cell.Route}";
            var method = cell.Method.ToUpperInvariant() switch
            {
                "POST" => "MapPost",
                "PUT" => "MapPut",
                "DELETE" => "MapDelete",
                "PATCH" => "MapPatch",
                _ => "MapGet"
            };

            sb.AppendLine($"// Endpoint: {cell.Title}");
            sb.AppendLine($"app.{method}(\"{route}\", (HttpContext context) =>");
            sb.AppendLine("{");
            foreach (var line in cell.Source.Split('\n'))
            {
                sb.AppendLine("    " + line.TrimEnd('\r'));
            }
            sb.AppendLine("});");
            sb.AppendLine();
        }

        sb.AppendLine($"app.Run(\"{document.ServerConfig.Scheme}://{document.ServerConfig.Host}:{document.ServerConfig.Port}\");");
        return sb.ToString();
    }
}

public static class FryServerCurlGenerator
{
    public static string GenerateCurlCommand(FryServerConfiguration config, FryServerCellItem cell)
    {
        var prefix = config.ApiPrefix?.TrimEnd('/') ?? string.Empty;
        if (!string.IsNullOrEmpty(prefix) && !prefix.StartsWith('/')) prefix = "/" + prefix;

        var route = $"{prefix}{cell.Route}";
        foreach (var p in cell.TestHarness.PathParams)
        {
            route = route.Replace($"{{{p.Key}}}", p.Value);
        }

        var qs = string.Join("&", cell.TestHarness.QueryParams.Select(kv => $"{kv.Key}={kv.Value}"));
        if (!string.IsNullOrEmpty(qs))
        {
            route += "?" + qs;
        }

        var fullUrl = $"{config.Scheme}://{config.Host}:{config.Port}{route}";
        var method = (cell.Method ?? "GET").ToUpperInvariant();

        var sb = new StringBuilder();
        sb.Append($"curl -X {method} \"{fullUrl}\"");

        foreach (var h in cell.TestHarness.Headers)
        {
            sb.Append($" -H \"{h.Key}: {h.Value}\"");
        }

        if (method is "POST" or "PUT" or "PATCH" && !string.IsNullOrWhiteSpace(cell.TestHarness.Body))
        {
            sb.Append($" -H \"Content-Type: {cell.TestHarness.BodyContentType}\"");
            var escapedBody = cell.TestHarness.Body.Replace("\"", "\\\"");
            sb.Append($" -d \"{escapedBody}\"");
        }

        return sb.ToString();
    }
}
