using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using FrySharp.Sdk;

namespace PdfEditorApp.Plugins.CSharpEditor.Services.Extensibility.Theming.ColorMath;

/// <summary>
/// Multi-format design system exporter generating Avalonia XAML, CSS Custom Properties,
/// Tailwind CSS configuration, and W3C DTCG / Figma token JSON files from generated themes.
/// </summary>
public static class ThemeExportService
{
    /// <summary>
    /// Exports the theme as an Avalonia ResourceDictionary XAML snippet.
    /// </summary>
    public static string ExportToAvaloniaXaml(ThemeDefinition theme)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"""
<!--
  FrySharp Generated Theme: {theme.Name} ({theme.Id})
  Harmonic Design System for Avalonia UI (.NET 10)
-->
<ResourceDictionary xmlns="https://github.com/avaloniaui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
""");

        foreach (var (key, hex) in theme.Colors)
        {
            sb.AppendLine($"""  <SolidColorBrush x:Key="{key}" Color="{hex}" />""");
        }

        sb.AppendLine("</ResourceDictionary>");
        return sb.ToString();
    }

    /// <summary>
    /// Exports the theme as CSS custom properties with light and dark root scopes.
    /// </summary>
    public static string ExportToCssVariables(ThemeDefinition lightTheme, ThemeDefinition darkTheme)
    {
        var sb = new StringBuilder();
        sb.AppendLine($$"""
/*
  ColorGene / FrySharp Design System Tokens
  Generated on {{DateTime.UtcNow:yyyy-MM-dd}}
*/

:root {
""");
        foreach (var (key, hex) in lightTheme.Colors)
        {
            string cssVar = "--" + key.Replace("Brush", "").ToLowerInvariant();
            sb.AppendLine($"  {cssVar}: {hex};");
        }

        sb.AppendLine("""
}

[data-theme="dark"] {
""");
        foreach (var (key, hex) in darkTheme.Colors)
        {
            string cssVar = "--" + key.Replace("Brush", "").ToLowerInvariant();
            sb.AppendLine($"  {cssVar}: {hex};");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Exports the theme in standard W3C Design Tokens Community Group (DTCG) JSON format.
    /// </summary>
    public static string ExportToDtcgJson(ThemeDefinition theme)
    {
        var root = new Dictionary<string, object>();
        var colors = new Dictionary<string, object>();

        foreach (var (key, hex) in theme.Colors)
        {
            colors[key] = new Dictionary<string, string>
            {
                ["$value"] = hex,
                ["$type"] = "color"
            };
        }

        root["color"] = colors;
        root["$description"] = theme.Description;

        return JsonSerializer.Serialize(root, new JsonSerializerOptions { WriteIndented = true });
    }

    /// <summary>
    /// Exports the theme as Tailwind CSS v4 @theme directive or v3 module export.
    /// </summary>
    public static string ExportToTailwindV4(ThemeDefinition theme)
    {
        var sb = new StringBuilder();
        sb.AppendLine("""
/* Tailwind CSS v4 @theme configuration */
@theme {
""");
        foreach (var (key, hex) in theme.Colors)
        {
            string twName = "--color-" + key.Replace("Brush", "").ToLowerInvariant();
            sb.AppendLine($"  {twName}: {hex};");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Exports the theme as a SwiftUI Color extension for iOS and macOS.
    /// </summary>
    public static string ExportToSwiftUI(ThemeDefinition theme)
    {
        var sb = new StringBuilder();
        sb.AppendLine($$"""
//
//  {{theme.Name}}Tokens.swift
//  Generated by FrySharp Color Studio on {{DateTime.UtcNow:yyyy-MM-dd}}
//

import SwiftUI

public extension Color {
""");
        foreach (var (key, hex) in theme.Colors)
        {
            string swiftName = char.ToLowerInvariant(key[0]) + key[1..].Replace("Brush", "");
            sb.AppendLine($"    static let {swiftName} = Color(hex: \"{hex}\")");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Exports the theme as a Jetpack Compose Color tokens object for Android.
    /// </summary>
    public static string ExportToJetpackCompose(ThemeDefinition theme)
    {
        var sb = new StringBuilder();
        string objName = "ThemeTokens";
        sb.AppendLine($$"""
package com.frysharp.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * {{theme.Name}} ({{theme.Id}})
 * Generated by FrySharp Color Studio on {{DateTime.UtcNow:yyyy-MM-dd}}
 */
object {{objName}} {
""");
        foreach (var (key, hex) in theme.Colors)
        {
            string ktName = char.ToLowerInvariant(key[0]) + key[1..].Replace("Brush", "");
            string cleanHex = hex.TrimStart('#');
            if (cleanHex.Length == 6) cleanHex = "FF" + cleanHex;
            sb.AppendLine($"    val {ktName} = Color(0x{cleanHex.ToUpperInvariant()}L)");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Imports a theme from standard W3C DTCG / Figma design tokens JSON.
    /// </summary>
    public static ThemeDefinition ImportFromDtcgJson(string json, string themeId = "imported-dtcg", string themeName = "Imported Theme", bool isDark = true)
    {
        var colors = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        JsonElement colorContainer = root;
        if (root.TryGetProperty("color", out var colorEl))
        {
            colorContainer = colorEl;
        }

        foreach (var prop in colorContainer.EnumerateObject())
        {
            if (prop.Value.ValueKind == JsonValueKind.Object && prop.Value.TryGetProperty("$value", out var valProp))
            {
                colors[prop.Name] = valProp.GetString() ?? "#000000";
            }
            else if (prop.Value.ValueKind == JsonValueKind.String)
            {
                colors[prop.Name] = prop.Value.GetString() ?? "#000000";
            }
        }

        var theme = new ThemeDefinition
        {
            Id = themeId,
            Name = themeName,
            Description = "Imported W3C DTCG token design system",
            IsDark = isDark,
            Colors = colors
        };

        HarmonicColorGenerator.EnsureCompleteTheme(theme);
        return theme;
    }
}
