using System.Security.Cryptography;
using System.Text;

namespace PdfEditorApp.Plugins.CSharpEditor.Services.Languages.Rust;

/// <summary>Where a staged script's Cargo package, shared build folder and finished program are.</summary>
/// <param name="ProjectDir">The generated package folder (holds <c>Cargo.toml</c> and cargo's <c>Cargo.lock</c>).</param>
/// <param name="ManifestPath">The generated <c>Cargo.toml</c>.</param>
/// <param name="PackageName">The package and program name: the file's name made a valid crate name, plus a short id.</param>
/// <param name="TargetDir">The build folder shared by every script, so each crate compiles once.</param>
/// <param name="ProfileDir"><c>debug</c> or <c>release</c>: the folder of <paramref name="TargetDir"/> the program lands in.</param>
/// <param name="BinPath">The built program.</param>
public sealed record RustStage(string ProjectDir, string ManifestPath, string PackageName, string TargetDir, string ProfileDir, string BinPath);

/// <summary>
/// Turns a Rust source file into a Cargo package cargo can build without touching the file's own folder. The manifest points
/// its one binary at the file where it is, so <c>mod x;</c> siblings, compiler messages and debug info all name the real file.
/// The package folder is stable for a given file (a SHA-256 of its path, not a per-process string hash), which lets cargo
/// reuse its work from one run to the next.
/// </summary>
public static class RustProjectStager
{
    public static RustStage Prepare(string rustRoot, string sourceFilePath, RustDirectives directives, string? displayCrateDir, bool isWindows)
    {
        var id = StableId(sourceFilePath);
        var projectDir = Path.Combine(rustRoot, "projects", id);
        var packageName = PackageNameFor(sourceFilePath, id);
        var targetDir = Path.Combine(rustRoot, "target");
        var profileDir = directives.Release ? "release" : "debug";
        var binPath = Path.Combine(targetDir, profileDir, isWindows ? packageName + ".exe" : packageName);

        var manifestPath = Path.Combine(projectDir, "Cargo.toml");
        WriteIfChanged(projectDir, manifestPath, BuildManifest(packageName, sourceFilePath, directives, displayCrateDir));

        return new RustStage(projectDir, manifestPath, packageName, targetDir, profileDir, binPath);
    }

    /// <summary>The <c>Cargo.toml</c> text for a script.</summary>
    public static string BuildManifest(string packageName, string sourceFilePath, RustDirectives directives, string? displayCrateDir)
    {
        var manifest = new StringBuilder();
        manifest.Append("# Generated by C# Code Studio for a single Rust file; changes are overwritten on the next run.\n");
        manifest.Append("[package]\n");
        manifest.Append("name = ").Append(TomlString(packageName)).Append('\n');
        manifest.Append("version = \"0.1.0\"\n");
        manifest.Append("edition = ").Append(TomlString(directives.Edition)).Append('\n');
        manifest.Append("publish = false\n");
        manifest.Append("autobins = false\nautoexamples = false\nautotests = false\nautobenches = false\n\n");

        manifest.Append("[[bin]]\n");
        manifest.Append("name = ").Append(TomlString(packageName)).Append('\n');
        manifest.Append("path = ").Append(TomlString(sourceFilePath)).Append("\n\n");

        manifest.Append("[dependencies]\n");
        if (!string.IsNullOrEmpty(displayCrateDir))
        {
            manifest.Append(RustDirectives.DisplayCrateName).Append(" = { path = ").Append(TomlString(displayCrateDir)).Append(" }\n");
        }

        foreach (var crate in directives.Crates) manifest.Append(crate.ToManifestLine()).Append('\n');

        // An empty workspace keeps cargo from attaching this package to a Cargo.toml in some parent folder.
        manifest.Append("\n[workspace]\n");
        return manifest.ToString();
    }

    /// <summary>A short, stable id for a file's path.</summary>
    public static string StableId(string sourceFilePath)
    {
        var normalized = sourceFilePath.Replace('\\', '/');
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(normalized));
        return Convert.ToHexString(hash)[..12].ToLowerInvariant();
    }

    /// <summary>
    /// <c>01. Two Sum.rs</c> → <c>two_sum_1a2b3c</c>: lower-case letters, digits and underscores, starting with a letter, and
    /// ending in part of the path's id so two files with one name never write the same program.
    /// </summary>
    public static string PackageNameFor(string sourceFilePath, string id)
    {
        var stem = Path.GetFileNameWithoutExtension(sourceFilePath.Replace('\\', '/'));
        return SanitizeCrateName(stem) + "_" + id[..6];
    }

    public static string SanitizeCrateName(string? stem)
    {
        var name = new StringBuilder();
        var lastWasUnderscore = false;
        foreach (var ch in (stem ?? string.Empty).ToLowerInvariant())
        {
            var keep = ch is (>= 'a' and <= 'z') or (>= '0' and <= '9');
            if (keep)
            {
                name.Append(ch);
                lastWasUnderscore = false;
            }
            else if (!lastWasUnderscore)
            {
                name.Append('_');
                lastWasUnderscore = true;
            }
        }

        // A crate name can't start with a digit.
        var text = name.ToString().Trim('_');
        var start = 0;
        while (start < text.Length && (text[start] is >= '0' and <= '9' || text[start] == '_')) start++;
        text = text[start..].Trim('_');
        return text.Length == 0 ? "main" : text;
    }

    /// <summary>A TOML string for a path or name: a literal string when possible, so Windows backslashes stay as they are.</summary>
    public static string TomlString(string value)
    {
        var needsEscapes = value.Any(c => c == '\'' || c == '\n' || c == '\r' || char.IsControl(c));
        if (!needsEscapes) return "'" + value + "'";

        var text = new StringBuilder("\"");
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': text.Append("\\\\"); break;
                case '"': text.Append("\\\""); break;
                case '\n': text.Append("\\n"); break;
                case '\r': text.Append("\\r"); break;
                case '\t': text.Append("\\t"); break;
                case var c when char.IsControl(c): text.Append("\\u").Append(((int)c).ToString("X4")); break;
                default: text.Append(ch); break;
            }
        }

        return text.Append('"').ToString();
    }

    // Rewriting an unchanged manifest would bump its timestamp and make cargo re-check the package.
    private static void WriteIfChanged(string projectDir, string path, string content)
    {
        try
        {
            Directory.CreateDirectory(projectDir);
            if (File.Exists(path) && File.ReadAllText(path) == content) return;
            File.WriteAllText(path, content, new UTF8Encoding(false));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new IOException($"Couldn't prepare the Rust build folder {projectDir}: {ex.Message}", ex);
        }
    }
}
